### ISSUE TITLE
d key bind is the same as j key bind

### ISSUE THREAD

**Issue by syphoxy** [osleg/Re-rodentbane#1]
for some reason, given the default bindings, my d and j button do the exact same function (resize to the bottom square). the problem: I can't resize to the bottom right square due to the bindings not working properly.

I haven't done any additional configurations outside of the defaults.

```
~ % awesome --version
awesome v3.5.2-530-g1e9da09 (The Fox)
 • Build: Jul 15 2015 10:20:41 for x86_64 by gcc version 5.1.1 (root@drusso-imac.demacmedia.com)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔
~ % 
```

I'm using current `awesomeWM/awesome` master.

thanks!

edit: btw, awesome work maintaining this!

**Comment by osleg** [comment]
Fixed :)

**Comment by syphoxy** [comment]
oh wow, that was easy. haha. thanks!

**Comment by osleg** [comment]
Basically it was just a fix that I forgot to push )
